### ISSUE TITLE
Pypi support

### ISSUE THREAD

**Issue by mengzhuo** [zeromq/pyre#14]
please add this repo into pypi.
BTW I found there is a project named "pyre" already.

**Comment by blink1073** [comment]
I asked the maintainer of the current `pyre` package on PyPI about its status and whether it was maintained, here the is the response:

```
Dear Steven,

Pyre is an application framework for scientific computing in active development since 1997.  I am not sure why its metadata on PyPI is broken, but I will fix it. I don’t know how to best approach the name conflict with your efforts.
```

**Comment by blink1073** [comment]
How about making it available as `pyzyre` on PyPI?  (Similar to `pyzmq`).

**Comment by koobs** [comment]
I'm (personal opinion) not a fan of "py" prefixed pypi packages, unless there is no alternative. What about zyre?

**Comment by blink1073** [comment]
Not a bad idea, @koobs.

**Comment by koobs** [comment]
@blink1073 And the Google Juice™ for users trying to find it is good :)

**Comment by sphaero** [comment]
Guess this is one for the ML as well. We decided on Pyre when this project was merged in to zeromq. Similar as Jyre, Gyre etc. There is already a pyzyre project I think.

**Comment by blink1073** [comment]
There is not `pyzyre` on Github or PyPI, and there is no `zyre` on PyPI.

**Comment by venabled** [comment]
+1 for `zyre`

**Comment by jfolz** [comment]
Any updates on this? I might use Zyre in a project to do discovery, but the ctypes/ffi bindings look less than pip-installable. I'm also not very keen on yet another dependency that needs the ``pip install --process-dependency-links``.

**Comment by sphaero** [comment]
You can use

    pip install https://github.com/zeromq/pyre/archive/master.zip

I'm not working on this currently but I think it's very easy to get done.

**Comment by jfolz** [comment]
OK, this seems to work fine, at least with current pip versions. This option does not seem to require the deprecated ``--process-dependency-links`` switch I mentioned earlier.

For future reference, you can put this in your ``requirements.txt``:

> https://github.com/zeromq/pyre/archive/b4f3497d14ee443871ae67fe9e643a1ef9f31ef1.zip#egg=pyre-0.3
pyre==0.3

It is generally not advisable to install the head of master. Since there don't seem to be releases yet, select a commit that works and stick with it.
You can get the direct link to a specific commit by pressing y on the project's main page, then copy the download zip link.
The hash part tells pip which package/version is hiding behind that link.

**Comment by brettviren** [comment]
Any more thoughts on getting "releases" of Pyre up on PyPI?

It seems in the mean time a fork, now out of date, has been uploaded to PyPI as "pyzyre".  @wesyoung are you maybe going to continue to update "pyzyre" on PyPI?

As far as PyPI names go, `zeromq-pyre` would be unambiguous.

**Comment by papr** [comment]
> pip install https://github.com/zeromq/pyre/archive/master.zip

Yes, thanks to PEP 508 one can specify a direct dependency like this
```
pyre @ https://github.com/zeromq/pyre/archive/master.zip
```

Unfortunately, packages using direct dependencies are not allowed to be uploaded to PyPI:
> Error: Can't have direct dependency : 'pyre @ https://github.com/zeromq/pyre/archive/master.zip'

**Comment by papr** [comment]
This issue can be closed as soon as the maintainers have
1. set up a repository secret named `PYPI_TOKEN` (read more about PyPI API tokens [here](https://pypi.org/help/#apitoken)
1. Creating and pushing a new tag to trigger the deployment

**Comment by papr** [comment]
This issue can finally be closed 🥳 https://pypi.org/project/zeromq-pyre/
