### ISSUE TITLE
We don't know peer id {0}

### ISSUE THREAD

**Issue by brettviren** [zeromq/pyre#145]
This code:

```python
import pyre
p1 = pyre.Pyre("p1")
p1.start()
p2 = pyre.Pyre("p2")
p2.start()
p1.stop()
p2.stop()
```

Gives this warning level log:

```
{}
We don't know peer id aa35f49f-f013-4500-a2c7-2b4f495a7b55
```

From this bit of Pyre code:
https://github.com/zeromq/pyre/blob/master/pyre/pyre_node.py#L480

Should I interpret the warning as something wrong with the test sequence?  

Thanks.

**Comment by sphaero** [comment]
This is probably due to the asynchronous behavior of the nodes. One node is already receiving an exit broadcast while it hasn't even registered the node yet. Probably if you add a sleep before stopping the nodes you won't see this.

**Comment by brettviren** [comment]
Adding a `time.sleep(1)` before the first `.stop()` indeed removes the warning.

It sounds like this is all okay behavior then.  Thanks, I'll close the issue.
