### ISSUE TITLE
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?"

### ISSUE THREAD

**Issue by hz-pupil** [zeromq/pyre#147]
Hi I am a freshman , when i follow the step at  https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md,
 "C:/Users/Administrator%3Epip install git+https://github.com/zeromq/pyre
Collecting git+https://github.com/zeromq/pyre
  Cloning https://github.com/zeromq/pyre to c:\users\admini~1\appdata\local\temp\pip-req-build-fr2df3zp
  Running command git clone -q https://github.com/zeromq/pyre 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-fr2df3zp'
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git clone -q https://github.com/zeromq/pyre 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-fr2df3zp'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?"
I don't know what's wrong and how to do next? Can some one help me?

**Comment by keent** [comment]
Familiarize yourself with the command line.
git is a command line tool.
better yet master linux immediately - so you can use any command, debug issues like this easily

**Comment by keent** [comment]
or use any shell in windows

**Comment by hz-pupil** [comment]
I cannot use git command at cmd. But I don't know why.

**Comment by hz-pupil** [comment]
https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md,   according the steps , I need to Install Python Libraries,   I copy "pip install win_inet_pton" to the  cmd, it's ok. But I copy "pip install git+https://github.com/zeromq/pyre",  it's errror.

**Comment by hz-pupil** [comment]
Also,  https://github.com/pupil-labs/pupil,  "After you have installed all dependencies, clone this repo and start Pupil software."  "git clone https://github.com/pupil-labs/pupil.git # or your fork", I still can not success this step.

**Comment by hz-pupil** [comment]
and then I download the files directly from "https://github.com/pupil-labs/pupil" and unwrap them to the "C:\work\pupil" , following the steps, but when want to start pupil, I use this command at cmd:  C:\work\pupil\pupil_src>run_capture.bat
it has this error: 
C:\work\pupil\pupil_src>SET PATH=C:\Python36\Scripts\;C:\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MATLAB\R2020a\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Python36;C:\work\pupil\pupil_external;;C:\work\pupil\pupil_src\..\pupil_external
C:\work\pupil\pupil_src>python main.py capture
Could not call git, is it installed? error msg: "[WinError 2] 系统找不到指定的文件。"
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    app_version = get_version()
  File "C:\work\pupil\pupil_src\shared_modules\version_utils.py", line 63, in get_version
    version = pupil_version()
  File "C:\work\pupil\pupil_src\shared_modules\version_utils.py", line 46, in pupil_version
    raise ValueError("Version Error")
ValueError: Version Error"

**Comment by hz-pupil** [comment]
I also open main.py at python IDE, and press F5 to run it, but, it has this error:
================== RESTART: C:\work\pupil\pupil_src\main.py ==================
main.py: error: the following arguments are required: <app>
usage: main.py [-h] <app> ...

positional arguments:
  <app>       which application to start
    capture   real-time processing and recording
    player    process, visualize, and export recordings
    service   low latency real-time processing with constrained feature set

optional arguments:
  -h, --help  show this help message and exit
>>>

**Comment by hz-pupil** [comment]
Please help me! Thank you for all.

**Comment by hz-pupil** [comment]
It's ok, I download the software of git . Thank you all.
