### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by smalls12** [zeromq/pyre#150]
Hello,

Just posing a question for any possible asyncio support.
I am working with zmq ( pyzmq ) where it supports asyncio out-of-box.
I had some plans to bring in pyre as well but it does not appear to support it out of box.

Any thoughts on this?

Thanks,

**Comment by smalls12** [comment]
Well if anyone is interested I started hacking this together.
Reusing pyre code and putting asyncio on top.
https://github.com/smalls12/aspyre

**Comment by sphaero** [comment]
Can you eleborate on what you needed to change? In theory you could just use the filedescriptor of pyre in async but I have no idea what it would take.

**Comment by fieldOfView** [comment]
I'm just here to applaud the name of @smalls12's project.

**Comment by smalls12** [comment]
> 
> 
> Can you eleborate on what you needed to change? In theory you could just use the filedescriptor of pyre in async but I have no idea what it would take.

The changes I am making will be a fundamental change to the backend of pyre.
Right now it uses zactor, threads and pipes to communicate with the different layers of pyre.
The different layers being:
1. Sending the beacon
2. Receiving beacons
3. Receiving on the router socket
4. Sending on peer dealer sockets
5. Waiting for user input

With asyncio, I will be swapping out all the zactor, threads and pipes and letting asyncio drive the app.

**Comment by smalls12** [comment]
> 
> 
> I'm just here to applaud the name of @smalls12's project.

lol yea if nothing else, it was nice how that worked out

**Comment by smalls12** [comment]
asyncio requires python3.6+ and the changes I am making our so significant that it may become its own standalone project while still making use of as much pyre code as possible.

I might be able to abstract as much as I can to limit duplication though.

**Comment by smalls12** [comment]
I've posted a working example on the README of my repo.
Maybe this can be closed and any further discussions moved there?
