### ISSUE TITLE
get_peer_name

### ISSUE THREAD

**Issue by shader** [zeromq/pyre#50]
get_peer_name() doesn't seem to be currently implemented.

It might make sense to add a get_peer() method that returns the peer object, which can be directly queried and manipulated, instead of always operating indirectly using uuids.

**Comment by sphaero** [comment]
There's a branch in which it is. We were still discussing the implementation in Zyre.

**Comment by shader** [comment]
Ok, I found the branch on your fork of the repo. I'll use that commit locally until you settle on something.

**Comment by shader** [comment]
Solved by merge of pull request #47 in 2f14ddbab401d7e9e597a6b0c2b7f7101a82981e
