### ISSUE TITLE
ZActor has no send_multipart method

### ISSUE THREAD

**Issue by shader** [zeromq/pyre#51]
Attempting to send a list of strings via Pyre.whisper or Pyre.shout raises an exception because the ZActor.send_multipart method does not exist.

    File "/usr/lib64/python2.7/site-packages/pyre/pyre.py", line 117, in whisper
      self.actor.send_multipart(msg)
    AttributeError: 'ZActor' object has no attribute 'send_multipart'

**Comment by shader** [comment]
Ok, turns out that the ZRE protocol officially excludes sending multi-frame messages as part of a WHISPER or SHOUT. I guess I'll have to find some other way to transmit my message frames.

At the same time, this is still a bug because the list should be rejected at the top level Pyre.whisper and shout methods, instead of having them try to call a method which doesn't (and supposedly shouldn't) exist.

Incidentally, what is the justification for preventing multi-frame message contents? Couldn't the ZRE layer simply pass on any remaining frames as 'content' to the application? It seems more consistent with the rest of zeromq to support multi-frame messages.

**Comment by sphaero** [comment]
Yeah I have to fix this, it's a bit of a left over. Indeed there is no support for multipart messages. There's a big discussion on going about it. I have to look into this but a bit occupied currently.

**Comment by sphaero** [comment]
instead of doing self.actor.send_multipart(msg) you can do 
self.actor.send(msg, zmq.SNDMORE) for every individual frame
