### ISSUE TITLE
Error - Resource temporarily unavailable

### ISSUE THREAD

**Issue by utsavdrolia** [zeromq/pyre#52]
I was running 5 nodes on the same machine and after sometime (~3minutes), I got this error.

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyre/zbeacon.py", line 204, in __init__
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/pyre/zbeacon.py", line 395, in run
    self.recv()
  File "/usr/local/lib/python3.4/dist-packages/pyre/zbeacon.py", line 371, in recv
    self._pipe.send_unicode(peername, zmq.SNDMORE)
  File "/usr/local/lib/python3.4/dist-packages/zmq/sugar/socket.py", line 330, in send_string
    return self.send(u.encode(encoding), flags=flags, copy=copy)
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
  File "zmq/backend/cython/socket.pyx", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)
  File "zmq/backend/cython/socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)
  File "zmq/backend/cython/checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6112)
zmq.error.Again: Resource temporarily unavailable

Followed by unending messages:
WARNING:pyre.pyre_node:Peer None isn't ready

**Comment by sphaero** [comment]
Is this consistent behaviour? This error seems to indicate a node is gone or not responding. You didn't receive an error before? 
It could also mean that the pipe between the zbeacon thread and the PyreNode thread is gone, full or deadlocked.

**Comment by utsavdrolia** [comment]
No, the error is not consistent.
Would there be any other error message if the pipe is gone, full or
deadlocked?

**Comment by sphaero** [comment]
I'm not sure, I have experienced some deadlocks which I couldn't trace. That's the nasty thing about this asynchronous computing. I've created unittests for it in which I was able to reproduce it. It was solved by upgrading zmq. You could try that.

Though I would still like to be able to trace these errors better

**Comment by utsavdrolia** [comment]
I think I am running libzmq 4.0.4 - a further upgrade might be required?
Any numbers on what might saturate the pipes? 
It could be possible that I had a lot of messages back ’n’ forth between 2 nodes. However, I did that same test multiple times but got this error only a few times.
Will this library be updated any further? Or would python bindings for Zyre replace it?

**Comment by sphaero** [comment]
The lib will updated further. I'm using it myself a lot. It might be superseded by the zyre bindings but these depend on libzmq, czmq and zyre. Which is quite a lot. Pyre just depends on zmq. That's why it is used often in environments where these libs are difficult to install.

The high watermark is set 1000 by default for a pipe. 
https://github.com/zeromq/pyre/blob/master/pyre/zhelper.py#L15
For a zthread it's 100
https://github.com/zeromq/pyre/blob/master/pyre/zhelper.py#L43

But for the zactor I'm not sure. It's the zmq default.

I recall that when a water mark is reached you get the EAGAIN exception.

**Comment by utsavdrolia** [comment]
Do you mean this error - "zmq.error.Again: Resource temporarily unavailable" ??
That was the error I got. Is that different from the EAGAIN exception?

Also, isn't this library using zactors in place of zthreads? Or are there places where you use both?

So I take it that Pyre will be regularly upgraded - awesome :)
What exactly do you use it for now?

**Comment by sphaero** [comment]
We're using both zthread and zactor. Still need to move everything to zactor. If you could try raising the HWM for zthread in your tests. See if that helps. I do not expect 100 messages to queue up but you never know.

See: https://fosdem.org/2015/schedule/event/deviot02/
Hopefully the videos will be up soon

**Comment by utsavdrolia** [comment]
Interesting!
I guess you would be the right person to ask - Why not joyn AllJoyn? 
If you don't have an answer offhand, any articles you could point me to?

**Comment by sphaero** [comment]
Why should I? I know there are many IoT efforts but most of them are too complex.
My initial research can be found here: http://www.z25.org/static/_rd_/zocp_init_plab/index.html

**Comment by sphaero** [comment]
I was kind of curious why you suggested AllJoyn but can we close this issue anyways?

**Comment by utsavdrolia** [comment]
I was researching networks at the edge and had come across AllJoyn. But it seems a lot more centralized in its approach.
Yes, we should close this issue now :)
