### ISSUE TITLE
Multicast bug?

### ISSUE THREAD

**Issue by blink1073** [zeromq/pyre#60]
I noticed that it appears that https://github.com/zeromq/pyre/blob/master/pyre/zbeacon.py#L71 will never evaluate to `True`, since we set `self.broadcast` in `__init__`, and not again until after that line has been evaluated to `False`.  If this is a bug I can submit a PR to fix it.

**Comment by sphaero** [comment]
You're probably right, multicast is still experimental. It's not in Zyre and only in Pyre as a test. We've just refactored zbeacon to do the same as zyre's zbeacon. We haven't tested multicast yet. It's on the todo list :) A PR is very welcome.

**Comment by blink1073** [comment]
Fixed by #61.
