### ISSUE TITLE
Import error from zbeacon.py when importing pyre

### ISSUE THREAD

**Issue by AxelVoitier** [zeromq/pyre#64]
Hello,

When installing pyre with either "pip install https://github.com/zeromq/pyre/archive/master.zip" as per README.md or by git cloning the repo and doing "pip install -e ." I got import errors:

The first one was:
```
>>> import pyre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyre/__init__.py", line 3, in <module>
    from .pyre import Pyre
  File "pyre/pyre.py", line 10, in <module>
    from . import zbeacon
  File "pyre/zbeacon.py", line 32, in <module>
    from pyre.zactor import ZActor
ImportError: No module named zactor
```

I fixed it by doing "sed -i "s/pyre.zactor/.zactor/" pyre/zbeacon.py".

Then I got that one:
```
>>> import pyre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyre/__init__.py", line 3, in <module>
    from .pyre import Pyre
  File "pyre/pyre.py", line 10, in <module>
    from . import zbeacon
  File "pyre/zbeacon.py", line 33, in <module>
    from pyre import zhelper
ImportError: cannot import name zhelper
```

I fixed it by doing "sed -i "s/from pyre import zhelper/from . import zhelper/" pyre/zbeacon.py".

After that import pyre did not raised any further import error.

Cheers,
Axel

**Comment by AxelVoitier** [comment]
I see this might actually be because I tried it with python2, as I get other problems with the ipaddress module that requires a different syntax for py2 as well.

I hope I will be able to use pyre with other modules that are all compatible with py3 :).
Maybe you could add a note in the installation paragraph that pyre currently only support py3?


Cheers,
Axel

**Comment by AxelVoitier** [comment]
Well, turned out the libs (and their deps) I wanted to use are all py3 incompatible :(.

I modified pyre to work on py2. the changes are rather minimal (the two ones above + adding u in front of the strings given to ipaddress module).
The tests with py2 and py3 yield the same results than master version on py3.
Are you interested in a pull request?


Cheers,
Axel

**Comment by blink1073** [comment]
This is addressed in #62.

**Comment by sphaero** [comment]
Pyre is aimed at Python3. It's quite hard maintaining python 2 support. It prevents using many optimizations available for py3. However it's really amazing how much py2 is still out there.

**Comment by AxelVoitier** [comment]
Sad truth :(. And that's not helped by some projects using modules last released in 2006 and for which the source code is hard to find nowadays :(.

**Comment by sphaero** [comment]
It's big missed opportunity of the Python Foundation for not having a clearer path from python2 to 3. 
Anyway, there is a PR which brings back python 2, however it hasn't passed the tests yet: https://github.com/zeromq/pyre/pull/62

**Comment by AxelVoitier** [comment]
I confirm #62 works for me :).

However, on the topic of using py3, quite ironically pyzmq itself does not support py3 when you use greenlets. It makes use of gevent which is not yet py3 compatible (see zeromq/pyzmq#666)
So if you want to use py3 with pyzmq (and pyre) while using greenlets, you are stuck with using eventlet... which does not have a Poller for zmq... >_<.
The only other alternative would be greenhouse, but it does not support py3 neither.

(And I just can't use threads because another package I am using is broken when using threads on py3...)

It's the combination of packages that kill the py2 to py3 migration.

**Comment by sphaero** [comment]
I've never needed greenlets or any other of those packages and I've been using py3 exclusively. Better make sure who to depend on ;)
