### ISSUE TITLE
support for multicast

### ISSUE THREAD

**Issue by matthewatabet** [zeromq/pyre#71]
Hi!

Any plans to support multicast? The environment I'm working in requires discovery across subnets.

Thanks!

**Comment by sphaero** [comment]
It's already in there. There's just not yet a call to set the address. Have a look in zbeacon.py.

**Comment by matthewatabet** [comment]
hey @sphaero! I'm not quite sure I follow -- this line configures the beacon for broadcast, no?
https://github.com/zeromq/pyre/blob/master/pyre/zbeacon.py#L73

I'm interested in multicast or epgm support. But, I could be missing something here. Any pointers?

**Comment by sphaero** [comment]
The next if statement! 
Try to set 
self broadcast_address = MULTICAST_GRP
in __init__

Might work.

It still needs some refactoring...

**Comment by matthewatabet** [comment]
Thanks @sphaero!

Hmmm... I'm kinda new to network programming, so I might still be missing something (apologies if am). But, wouldn't we need to turn off SO_BROADCAST and possibly turn on IPPROTO_UDP?

Ala this example: http://stackoverflow.com/questions/603852/multicast-in-python

If we don't need to do this, do you have a quick example using multicast?

Thanks a bunch for your help!

**Comment by sphaero** [comment]
Just try it and if it fails create an issue or a pull request.

If you change 
self.broadcast_address = None
to
self.broadcast_address = MULTICAST_GRP

you should have multicast

**Comment by sphaero** [comment]
Can you close this issue if it is resolved for you?
