### ISSUE TITLE
No headers in ENTER msg

### ISSUE THREAD

**Issue by nhuebel** [zeromq/pyre#78]
I noticed this is a TODO with question marks in the `pyre_node.py`. Is there anybody working on it?

Since I need it for a project, I made a fix using JSON to serialise the header dict. I am happy to send a pull request if you are interested.

**Comment by sphaero** [comment]
Ah yes, that's a todo indeed. If you can make pr mimicking https://github.com/zeromq/zyre/blob/master/src/zyre_node.c 
However I'd go for pickle as its already used in pyre.

**Comment by nhuebel** [comment]
I was looking into the code the code a bit more and both options (JSON+pickle) are already implemented: https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py
So I will go with JSON. I'll add it to the `pyre_node.py` and adjust the README and example `chat.py` accordingly. Then I will send you a pr.

**Comment by sphaero** [comment]
Btw, If you can could you also add a unittest for this?

**Comment by nhuebel** [comment]
Sure, but it will take a few days since I am busy.
