### ISSUE TITLE
zbeacon.py binds to link-local interface

### ISSUE THREAD

**Issue by madarp** [zeromq/pyre#84]
Hi, I've been trying out Pyre for a work project.  On my windows desktop dev environment, I notice that during the zbeacon.py/_prepare_socket method, it will bind to any link-local interface on my system that is not disabled, such as secondary NIC or VPN.  When this happens, pyre cannot send or receive any messages.  Is link-local binding useful in a way I'm not considering?  If not, I have a patch to skip over link-local during interface selection.

**Comment by sphaero** [comment]
Sure, send in a PR
