### ISSUE TITLE
message.shout( ... ) and protobuf

### ISSUE THREAD

**Issue by python152** [zeromq/pyre#86]
hi - It seems shout() can only take a string type? 
is there anyway to make it work with a protobuf message type?

Thanks

**Comment by sphaero** [comment]
I think you are right. We need to fix this. I'm going to have a look at the reference and see whats best to fix this. Suggestions/patches/pr welcome

**Comment by sphaero** [comment]
On second thought the implementation is correct. You can only send bytes through pyre. So if you are using protobuf you need to send its bytes not the python object. To send strings you can you can use shouts or whispers. Please close the issue if this resolves it for you

**Comment by python152** [comment]
I think protobuf's `SerializeToString()` did the trick ... it converts python object to bytes. Closing.
